language: perl
perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
install:
    - cpanm --quiet --notest --skip-satisfied Devel::Cover
    - cpanm --quiet --notest --skip-satisfied Dist::Milla Git::Repository
    - cpanm --installdeps .
script:
    - milla smoke --release --author
after_success:
    - cover -report coveralls
